version: "3.8"

services:
  database:
    image: postgres
    container_name: prisma_deliveries
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma_deliveries
